export enum API {
  tenants = '/api/tenants',
  vehicles = '/api/vehicles',
  reservations = '/api/reservations',
  tickets = '/api/tickets',
  solveTicket = '/api/tickets/solve',
  incidents = '/api/incidents',
  insuranceCompanies = '/api/insurance-companies',
  reservationTemplates = '/api/reservation-templates',
  login = '/api/login',
  register = '/api/register',
  users = '/api/users',
  auth = '/api/auth',
  positions = '/api/positions',
  reservationReports = '/api/reservations/reports',
  monthlyReports = '/api/reports',
  dietReports = '/api/diet-reports',
  billingReports = '/api/billing-reports',
}
